const userSamples = [
    {
      "_id": "65f7a1b2c3d4e5f6a7b8c9d0",
      "username": "john_doe",
      "email": "john.doe@example.com",
      "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
      "avatar": "https://ui-avatars.com/api/?name=John+Doe&background=0D8ABC&color=fff",
      "streak": 5,
      "total_questions_attempted": 87,
      "total_correct_answers": 64,
      "badges": ["7-Day Streak"],
    },
    {
      "_id": "65f7a1b2c3d4e5f6a7b8c9d1",
      "username": "jane_smith",
      "email": "jane.smith@example.com",
      "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
      "avatar": "https://ui-avatars.com/api/?name=Jane+Smith&background=8A2BE2&color=fff",
      "streak": 12,
      "total_questions_attempted": 145,
      "total_correct_answers": 132,
      "badges": ["7-Day Streak", "Century Club"],
    },
    {
      "_id": "65f7a1b2c3d4e5f6a7b8c9d2",
      "username": "alex_kumar",
      "email": "alex.kumar@example.com",
      "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
      "avatar": "https://ui-avatars.com/api/?name=Alex+Kumar&background=FF4500&color=fff",
      "streak": 0,
      "total_questions_attempted": 56,
      "total_correct_answers": 41,
      "badges": [],
    },
    {
      "_id": "65f7a1b2c3d4e5f6a7b8c9d3",
      "username": "sarah_chen",
      "email": "sarah.chen@example.com",
      "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
      "avatar": "https://ui-avatars.com/api/?name=Sarah+Chen&background=20B2AA&color=fff",
      "streak": 23,
      "total_questions_attempted": 210,
      "total_correct_answers": 187,
      "badges": ["7-Day Streak", "Century Club"],
    },
    {
      "_id": "65f7a1b2c3d4e5f6a7b8c9d4",
      "username": "mike_johnson",
      "email": "mike.johnson@example.com",
      "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
      "avatar": "https://ui-avatars.com/api/?name=Mike+Johnson&background=DAA520&color=fff",
      "streak": 3,
      "total_questions_attempted": 42,
      "total_correct_answers": 28,
      "badges": [],
    },
    {
        "username": "alice_dev",
        "email": "alice@example.com",
        "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
        "avatar": "https://ui-avatars.com/api/?name=Alice+Dev&background=DAA520&color=fff",
        "streak": 3,
        "total_questions_attempted": 50,
        "total_correct_answers": 35,
        "badges": [],
      },
      {
        "username": "bob_coder",
        "email": "bob@example.com",
        "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
        "avatar": "https://ui-avatars.com/api/?name=Bob+Coder&background=DAA520&color=fff",
        "streak": 5,
        "total_questions_attempted": 80,
        "total_correct_answers": 65,
        "badges": [],
      },
      {
        "username": "charlie_js",
        "email": "charlie@example.com",
        "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
        "avatar": "https://ui-avatars.com/api/?name=Charlie+Js&background=DAA520&color=fff",
        "streak": 7,
        "total_questions_attempted": 120,
        "total_correct_answers": 95,
        "badges": [],
      },
      {
        "username": "david_es6",
        "email": "david@example.com",
        "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
        "avatar": "https://ui-avatars.com/api/?name=David+ES6&background=DAA520&color=fff",
        "streak": 2,
        "total_questions_attempted": 30,
        "total_correct_answers": 20,
        "badges": [],
      },
      {
        "username": "eve_async",
        "email": "eve@example.com",
        "password": "$2a$10$iHh8nQvHTgbGaoHYFjOFM.v4myXa5igEvoGULfG5fHFomWisHO1AK",
        "avatar": "https://ui-avatars.com/api/?name=Eve+Async&background=DAA520&color=fff",
        "streak": 8,
        "total_questions_attempted": 150,
        "total_correct_answers": 130,
        "badges": [],
      }
  ]

  export default userSamples;